project_id: poc-piloturl-nonprod
region: asia-southeast1
gcs_bucket: gs://poc-piloturl-hyde-item-pipeline/
bq_default_dataset: gold_layer
batch_paths:
  batch_root: gs://poc-piloturl-hyde-item-pipeline/batch_root/
  delete_root: gs://poc-piloturl-hyde-item-pipeline/batch_root/delete/
filters:
  restricts_fields:
  - level
  - category_id
  - category_name
  - sub_cat_name
  - skill_name
  - status
  - university
  numeric_restricts_fields:
  - created_at
  - updated_at
embedding:
  model_name: gemini-embedding-001
  output_dimensionality: 1000
  text_fields:
  - lesson_title
  - content_title
  - short_description
  - description
  metadata_fields:
  - id
  - link
  - lesson_title
resource_names:
  index_id: projects/810737581373/locations/asia-southeast1/indexes/8740365374865801216
  endpoint_id: projects/810737581373/locations/asia-southeast1/indexEndpoints/2127009641979183104
  deployed_index_id: items_deployed
index_defaults:
  shard_size: SHARD_SIZE_SMALL
  distance_measure_type: DOT_PRODUCT
  feature_norm_type: UNIT_L2_NORM
  index_update_method: STREAM_UPDATE
  approximate_neighbors_count: 150
  leaf_node_embedding_count: 1000
  leaf_nodes_to_search_percent: 5
